export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const INVALIDATE_CATEGORY = 'INVALIDATE_CATEGORY';
export const REQUEST_QUESTIONS = 'REQUEST_QUESTIONS';
export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';

export const SET_CURRENT_ANSWER = 'SET_CURRENT_ANSWER';
export const SET_CURRENT_ANSWER_STATUS = 'SET_CURRENT_ANSWER_STATUS';
export const SET_CURRENT_QUESTION_INDEX = 'SET_CURRENT_QUESTION_INDEX';
export const SET_DISPLAY_ANSWER_RESPONSE = 'SET_DISPLAY_ANSWER_RESPONSE';
export const SET_GAME_OVER = 'SET_GAME_OVER';
export const SET_SCORE = 'SET_SCORE';
