export const SET_CURRENT_ANSWER = 'SET_CURRENT_ANSWER';

export const SET_CURRENT_ANSWER_STATUS = 'SET_CURRENT_ANSWER_STATUS';

export const SET_DISPLAY_ANSWER_RESPONSE = 'SET_DISPLAY_ANSWER_RESPONSE';

export const SET_SCORE = 'SET_SCORE';
